#!/bin/sh

cd "$HOME"

# we hate submodules around here, TODO: fix this ugliness
rm -rf $ZSH_CUSTOM/plugins/zsh-autosuggestions $ZSH_CUSTOM/plugins/zsh-syntax-highlighting $HOME/.config/kitty-themes $HOME/.config/nerd-fonts $HOME/.oh-my-zsh $HOME/.config/nvim ~/.local/src/diff-so-fancy ~/.local/src/esh



# Install ohmyzsh, thanks nacho
export CHSH=no
export KEEP_ZSHRC=yes
export RUNZSH=no
ZSH= sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" || true
sudo chsh -s "$(which zsh)" "$USER" 

# zsh plugins
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

# kitty themeing
git clone --depth 1 https://github.com/dexpota/kitty-themes.git ~/.config/kitty-themes

# nerd font setup
# TODO: add a gaurd if font is already installed
git clone --filter=blob:none --sparse https://github.com/ryanoasis/nerd-fonts.git ~/.config/nerd-fonts
cd ~/.config/nerd-fonts
git sparse-checkout add patched-fonts/Mononoki
./install.sh Mononoki
cd "$HOME"

# git diff-so-fancy setup
git clone https://github.com/so-fancy/diff-so-fancy.git ~/.local/src/diff-so-fancy
mkdir -p $HOME/.local/bin
ln -s $HOME/.local/src/diff-so-fancy/diff-so-fancy $HOME/.local/bin/diff-so-fancy

# setup esh
git clone https://github.com/jirutka/esh.git ~/.local/src/esh
ln -s $HOME/.local/src/esh/esh $HOME/.local/bin/esh

# powerline10k setup
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k

# nvim setup
git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1 

yadm checkout .

exec zsh
